// Generates the terminal intro frames from the logo, ONCE (dev only, macOS):
//   npx tsx tools/gen-intro.ts
// It uses `sips` (built into macOS) to turn the PNG into a BMP, reads the pixels itself,
// rotates them, and writes Braille text to src/cli/intro-frames.ts. At runtime the CLI only
// prints that text: no image libraries, no dependencies.
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { toBraille } from "./braille.ts";

const LOGO = join(import.meta.dirname, "..", "..", "brand", "logo", "agentcollar-mark-black.png");
const OUT = join(import.meta.dirname, "..", "src", "cli", "intro-frames.ts");
const SUPERSAMPLE = 4; // each output dot looks at 4×4 source pixels, so edges stay smooth

type Mask = { size: number; ink: (x: number, y: number) => boolean };

// "Ink" = a visible dark pixel. The letters AC are transparent holes in the dark medallion.
function loadMask(size: number): Mask {
  const bmp = join(mkdtempSync(join(tmpdir(), "intro-")), "mark.bmp");
  execFileSync("sips", ["-s", "format", "bmp", "-z", String(size), String(size), LOGO, "--out", bmp], { stdio: "ignore" });
  const b = readFileSync(bmp);
  const offset = b.readUInt32LE(10);
  const width = b.readInt32LE(18);
  const height = b.readInt32LE(22); // negative = rows stored top to bottom
  const bytesPerPixel = b.readUInt16LE(28) / 8;
  const rowBytes = Math.ceil((width * bytesPerPixel) / 4) * 4;
  return {
    size,
    ink(x, y) {
      if (x < 0 || y < 0 || x >= width || y >= Math.abs(height)) return false;
      const row = height < 0 ? y : Math.abs(height) - 1 - y;
      const p = offset + row * rowBytes + x * bytesPerPixel;
      const [blue, green, red] = [b[p]!, b[p + 1]!, b[p + 2]!];
      const alpha = bytesPerPixel === 4 ? b[p + 3]! : 255;
      return alpha > 128 && (red + green + blue) / 3 < 128;
    },
  };
}

// The medallion at `dotsWide` dots, turned clockwise by `angle` degrees, as Braille lines.
function render(mask: Mask, dotsWide: number, angle: number): string[] {
  const scale = mask.size / dotsWide;
  const center = mask.size / 2;
  const cos = Math.cos((-angle * Math.PI) / 180);
  const sin = Math.sin((-angle * Math.PI) / 180);
  const dots: boolean[][] = [];
  for (let y = 0; y < dotsWide; y++) {
    const row: boolean[] = [];
    for (let x = 0; x < dotsWide; x++) {
      let hits = 0;
      for (let sy = 0; sy < SUPERSAMPLE; sy++) {
        for (let sx = 0; sx < SUPERSAMPLE; sx++) {
          // where does this sub-dot come from in the un-rotated picture?
          const px = (x + (sx + 0.5) / SUPERSAMPLE) * scale - center;
          const py = (y + (sy + 0.5) / SUPERSAMPLE) * scale - center;
          const srcX = Math.floor(px * cos - py * sin + center);
          const srcY = Math.floor(px * sin + py * cos + center);
          if (mask.ink(srcX, srcY)) hits++;
        }
      }
      row.push(hits > (SUPERSAMPLE * SUPERSAMPLE) / 2);
    }
    dots.push(row);
  }
  return toBraille(dots);
}

const big = loadMask(48 * SUPERSAMPLE);
const spin = Array.from({ length: 12 }, (_, i) => render(big, 48, i * 30));
const shrink = [32, 20, 12].map((dots) => render(loadMask(dots * SUPERSAMPLE), dots, 0));
const icon = render(loadMask(8 * SUPERSAMPLE), 8, 0);

const list = (frames: string[][]) => `[\n${frames.map((f) => `  ${JSON.stringify(f)},`).join("\n")}\n]`;
writeFileSync(
  OUT,
  `// GENERATED by tools/gen-intro.ts from brand/logo/agentcollar-mark-black.png. Do not edit by hand.
// Derived from the AgentCollar mark: © 2026 ank8dev, all rights reserved (NOT covered by the MIT license).

// The medallion, 48×48 dots (24 columns × 12 rows), turned 0°, 30°, … 330° clockwise.
export const SPIN: string[][] = ${list(spin)};

// Upright and smaller (32, 20, 12 dots): the medallion "flies" into the header.
export const SHRINK: string[][] = ${list(shrink)};

// 8×8 dots: the small mark in the header.
export const ICON: string[] = ${JSON.stringify(icon)};
`,
);
console.log(`wrote ${OUT}`);
console.log([...spin[0]!, "", ...spin[3]!, "", ...icon].join("\n"));
