// Builds the documentation pages, one per language, from:
//   docs/content/<lang>.html  - the translated text (main column only)
//   docs/content/code.html    - code, terminal output and diagrams, shared by every language
// Output: docs/index.html (English) and docs/<lang>/index.html. Vite then builds them like
// any other page. Run: node scripts/build-docs.mjs (also part of `npm run build`).

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const docsDir = join(root, 'docs');

// English first; the rest are the 9 most used languages for developer docs (no Russian).
export const LANGS = [
  { code: 'en', name: 'English', path: '' },
  { code: 'zh', name: '简体中文', path: 'zh/', html: 'zh-Hans' },
  { code: 'es', name: 'Español', path: 'es/' },
  { code: 'hi', name: 'हिन्दी', path: 'hi/' },
  { code: 'ar', name: 'العربية', path: 'ar/', dir: 'rtl' },
  { code: 'pt', name: 'Português', path: 'pt/', html: 'pt-BR' },
  { code: 'fr', name: 'Français', path: 'fr/' },
  { code: 'de', name: 'Deutsch', path: 'de/' },
  { code: 'ja', name: '日本語', path: 'ja/' },
  { code: 'ko', name: '한국어', path: 'ko/' },
];

// Small interface words around the content, per language.
const UI = {
  en: { contents: 'Contents', language: 'Language', copy: 'copy', copied: 'copied', star: 'Star on GitHub', skip: 'Skip to content' },
  zh: { contents: '目录', language: '语言', copy: '复制', copied: '已复制', star: 'Star on GitHub', skip: '跳到正文' },
  es: { contents: 'Contenido', language: 'Idioma', copy: 'copiar', copied: 'copiado', star: 'Star on GitHub', skip: 'Ir al contenido' },
  hi: { contents: 'विषय-सूची', language: 'भाषा', copy: 'कॉपी', copied: 'कॉपी हुआ', star: 'Star on GitHub', skip: 'सामग्री पर जाएँ' },
  ar: { contents: 'المحتويات', language: 'اللغة', copy: 'نسخ', copied: 'تم النسخ', star: 'Star on GitHub', skip: 'انتقل إلى المحتوى' },
  pt: { contents: 'Conteúdo', language: 'Idioma', copy: 'copiar', copied: 'copiado', star: 'Star on GitHub', skip: 'Ir para o conteúdo' },
  fr: { contents: 'Sommaire', language: 'Langue', copy: 'copier', copied: 'copié', star: 'Star on GitHub', skip: 'Aller au contenu' },
  de: { contents: 'Inhalt', language: 'Sprache', copy: 'kopieren', copied: 'kopiert', star: 'Star on GitHub', skip: 'Zum Inhalt' },
  ja: { contents: '目次', language: '言語', copy: 'コピー', copied: 'コピー済み', star: 'Star on GitHub', skip: '本文へ移動' },
  ko: { contents: '목차', language: '언어', copy: '복사', copied: '복사됨', star: 'Star on GitHub', skip: '본문으로 건너뛰기' },
};

const SITE = 'https://ank8dev.github.io/agentcollar/';

// --- shared code blocks -------------------------------------------------------------
function readCodeBlocks() {
  const text = readFileSync(join(docsDir, 'content', 'code.html'), 'utf8');
  const blocks = {};
  const parts = text.split(/<!-- @code ([\w-]+) -->\n/);
  for (let i = 1; i < parts.length; i += 2) blocks[parts[i]] = parts[i + 1].trim();
  return blocks;
}

// --- contents list from the headings -------------------------------------------------
const stripTags = (html) => html.replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();

function buildToc(main) {
  const items = [];
  const sectionRe = /<section id="([\w-]+)">\s*<h2 class="sec">([\s\S]*?)<\/h2>([\s\S]*?)<\/section>/g;
  for (const [, id, title, body] of main.matchAll(sectionRe)) {
    items.push(`<li><a href="#${id}">${stripTags(title)}</a></li>`);
    // only the h3 subsections of "How it works" go into the list (the rest stay short)
    if (id === 'concepts') {
      for (const [, subId, subTitle] of body.matchAll(/<h3 id="([\w-]+)">([\s\S]*?)<\/h3>/g)) {
        items.push(`<li class="sub"><a href="#${subId}">${stripTags(subTitle)}</a></li>`);
      }
    }
  }
  return items.join('\n          ');
}

// --- the page shell --------------------------------------------------------------------
function page(lang, meta, main, code) {
  const ui = UI[lang.code];
  const up = lang.path ? '../' : ''; // relative link back to docs/
  const body = main.replace(/\{\{([\w-]+)\}\}/g, (_, id) => {
    if (!(id in code)) throw new Error(`${lang.code}: unknown code block {{${id}}}`);
    return code[id].replaceAll('>copy</button>', `>${ui.copy}</button>`);
  });
  const alternates = LANGS.map(
    (l) => `<link rel="alternate" hreflang="${l.html ?? l.code}" href="${SITE}docs/${l.path}" />`,
  ).join('\n    ');
  const options = LANGS.map(
    (l) => `<option value="${up}${l.path || './'}"${l.code === lang.code ? ' selected' : ''} lang="${l.html ?? l.code}">${l.name}</option>`,
  ).join('');

  return `<!doctype html>
<!-- Generated by scripts/build-docs.mjs from docs/content/${lang.code}.html: edit that file, not this one. -->
<html lang="${lang.html ?? lang.code}" dir="${lang.dir ?? 'ltr'}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
    <title>${meta.title}</title>
    <meta name="description" content="${meta.description}" />
    <meta name="theme-color" content="#f0f6e7" />
    <link rel="icon" href="/brand/logo/agentcollar-mark-black.svg" type="image/svg+xml" />
    <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
    ${alternates}
    <link rel="alternate" hreflang="x-default" href="${SITE}docs/" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Special+Elite&family=Courier+Prime:ital,wght@0,400;0,700;1,400;1,700&family=Intel+One+Mono:ital,wght@0,400;0,600;1,400&display=swap" />
    <link rel="stylesheet" href="/docs/docs.css" />
  </head>
  <body data-copied="${ui.copied}" data-copy="${ui.copy}">
    <a class="skip" href="#content">${ui.skip}</a>

    <header class="site-header">
      <a class="site-header__mark" href="${SITE}" aria-label="AgentCollar website"><img src="/brand/logo/agentcollar-mark-black.svg" alt="" width="34" height="34" /></a>
      <a class="site-header__star" href="https://github.com/ank8dev/agentcollar"><span class="star-icon" aria-hidden="true"></span>${ui.star}</a>
      <a class="site-header__wordmark" href="${SITE}">AgentCollar <span class="docs-tag">docs</span></a>
    </header>

    <div class="wrap">
      <aside class="toc" aria-label="${ui.contents}">
        <label class="lang"><span class="visually-hidden">${ui.language}</span>
          <select id="lang" aria-label="${ui.language}">${options}</select>
        </label>
        <h2>${ui.contents}</h2>
        <ol id="toc">
          ${buildToc(main)}
        </ol>
      </aside>

      <main id="content">
${body}
      </main>
    </div>

    <footer class="doc-foot">
      <div class="doc-foot__sky" aria-hidden="true">
        <img class="doc-foot__earth" src="/brand/pictures/agentcollar-earth.webp" alt="" width="886" height="927" loading="lazy" />
      </div>
      <div class="doc-foot__bar">
        <a class="doc-foot__brand" href="${SITE}"><img src="/brand/logo/agentcollar-mark-white.svg" alt="" width="40" height="40" />AgentCollar</a>
        <p class="doc-foot__tagline">Let agents work. Keep the keys.</p>
        <nav class="doc-foot__links" aria-label="Links">
          <a href="${SITE}">Website</a>
          <a href="https://github.com/ank8dev/agentcollar">GitHub</a>
          <a href="https://www.npmjs.com/package/agentcollar">npm</a>
          <a href="https://x.com/ank8dev">X</a>
        </nav>
        <p class="doc-foot__legal">Code MIT · brand © ank8dev · ${new Date().getFullYear()}</p>
      </div>
    </footer>

    <script type="module" src="/docs/docs.js"></script>
  </body>
</html>
`;
}

// --- build -------------------------------------------------------------------------------
function parseMeta(text) {
  const m = text.match(/^<!--meta\n([\s\S]*?)\n-->\n/);
  if (!m) throw new Error('missing <!--meta ... --> header');
  const meta = Object.fromEntries(m[1].split('\n').map((line) => [line.split(':')[0].trim(), line.slice(line.indexOf(':') + 1).trim()]));
  return { meta, main: text.slice(m[0].length) };
}

const code = readCodeBlocks();
const built = [];
// a language without its content file yet is left out (and out of the switcher)
const available = LANGS.filter((l) => existsSync(join(docsDir, 'content', `${l.code}.html`)));
LANGS.splice(0, LANGS.length, ...available);
for (const lang of LANGS) {
  const { meta, main } = parseMeta(readFileSync(join(docsDir, 'content', `${lang.code}.html`), 'utf8'));
  const out = join(docsDir, lang.path, 'index.html');
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, page(lang, meta, main, code));
  built.push(lang.code);
}
console.log(`docs: built ${built.join(', ')}`);
